//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHotel_v1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Modelo\\bdSist" +
            "emaHotel.mdf;Integrated Security=True")]
        public string bdSistemaHotelConnectionString {
            get {
                return ((string)(this["bdSistemaHotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=""C:\USERS\GABRIELA ASTUDILLO\DOCUMENTS\VISUAL STUDIO 2017\PROJECTS\SISTEMAHOTEL_V1\SISTEMAHOTEL_V1\MODELO\BDSISTEMAHOTEL.MDF"";Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True")]
        public string C__USERS_GABRIELA_ASTUDILLO_DOCUMENTS_VISUAL_STUDIO_2017_PROJECTS_SISTEMAHOTEL_V1_SISTEMAHOTEL_V1_MODELO_BDSISTEMAHOTEL_ {
            get {
                return ((string)(this["C__USERS_GABRIELA_ASTUDILLO_DOCUMENTS_VISUAL_STUDIO_2017_PROJECTS_SISTEMAHOTEL_V1" +
                    "_SISTEMAHOTEL_V1_MODELO_BDSISTEMAHOTEL_"]));
            }
        }
    }
}
